version: '3.9'
services:
  web-ui:
    image: web-ui:latest
    env_file:
      - .env
    expose:
      - 4200
    ports:
      - 4200:4200
  fibonacci-calculator:
    image: fibonacci-calculator:latest
    ports:
      - 8080:8080
