---
name: Blue Green Deployment
on:
  push:
    branches: ["main"]
jobs:
  read-yaml-deployment-environment:
    runs-on: ubuntu-latest
    name: read-yaml
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main
        with:
          file: ".deployment.yml"
          key-path: '["environment"]'
      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"
    outputs:
      environment: ${{ steps.yaml-data.outputs.data }}
  deploy:
    environment:
      name: ${{ needs.read-yaml-deployment-environment.outputs.environment }}
      url: ${{ needs.read-yaml-deployment-environment.outputs.environment }}
    runs-on: ubuntu-latest
    needs: read-yaml-deployment-environment
    steps:
      - name: Deploy to Blue Green Environment
        id: deployment
        run: >
          echo ${{ needs.read-yaml-deployment-environment.outputs.environment }}
