---
name: Blue Green Deployment
on:
  workflow_run:
    workflows: ["Test and Publish Maven and Docker Packages"]
    branches: [main]
    types:
      - completed
jobs:
  read-yaml:
    runs-on: ubuntu-latest
    name: read-yaml
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main
        with:
          file: ".environment.yml"
          key-path: '["environment"]'
      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"
    outputs:
      environment: ${{ steps.yaml-data.outputs.data }}
  deploy:
    environment:
      name: ${{ needs.read-yaml.outputs.environment }}
      url: https://${{ needs.read-yaml.outputs.environment }}.cqa-demo.io
    runs-on: ubuntu-latest
    needs: read-yaml
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Blue Green Environment
        id: deployment
        uses: ./.github/actions/blue-green-deployment
        with:
          AZ_USER_NAME: ${{ secrets.AZ_CLIENT_ID }}
          AZ_PASSWORD: ${{ secrets.AZ_CLIENT_SECRET }}
          AZ_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
          AZ_RESOURCE_GROUP_NAME: ${{ secrets.AZ_RESOURCE_GROUP_NAME }}
          AZ_AKS_CLUSTER_NAME: ${{ secrets.AZ_AKS_CLUSTER_NAME }}
          VERSION: ${{ github.sha }}
          ENVIRONMENT: ${{ needs.read-yaml.outputs.environment }}
