---
name: Blue Green Deployment
on:
  push:
    branches: ["main"]
jobs:
  read-yaml-deployment-environment:
    runs-on: ubuntu-latest
    name: read-yaml
    steps:
      - uses: actions/checkout@v1
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main
        with:
          file: './deployment.yml'
          key-path: '["environment"]'
      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"
