---
name: Grype Container Scan
on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build jar
        run: >
          cd ./micro-services/fibonacci-calculator
          && mvn --batch-mode package
      - name: Build the container image
        run: >
          docker build
          --file ./micro-services/fibonacci-calculator/Dockerfile
          --tag localbuild/testimage:latest
          ./micro-services/fibonacci-calculator
      - uses: anchore/scan-action@v3
        with:
          image: "localbuild/testimage:latest"
          fail-build: true
